'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USER1
    Public Property RID As Integer
    Public Property FNAME As String
    Public Property LNAME As String
    Public Property ADDR As String
    Public Property DESIG As String
    Public Property PHNO As String
    Public Property EMAIL As String
    Public Property UID As String
    Public Property PASS As String
    Public Property DPCODE As String

End Class
