//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST
    {
        public int CID { get; set; }
        public string CUST1 { get; set; }
        public string SECTOR { get; set; }
        public string DPCODE { get; set; }
    }
}
