//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMR
    {
        public int RECID1 { get; set; }
        public string SID { get; set; }
        public string SNAME { get; set; }
        public string ENGINE_No { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public string STYPE { get; set; }
        public string HMR { get; set; }
        public string Report { get; set; }
        public string Technician { get; set; }
        public string METERIAL { get; set; }
        public string CUST { get; set; }
        public string recid { get; set; }
        public Nullable<System.DateTime> CDATI { get; set; }
        public string DIST { get; set; }
        public string STATE { get; set; }
        public string CCATE { get; set; }
        public string MODEL { get; set; }
        public Nullable<System.DateTime> DOI { get; set; }
        public string DGNO { get; set; }
        public string AMAKE { get; set; }
        public string ALSN { get; set; }
        public string BSN { get; set; }
        public string CNAT { get; set; }
        public string SERV { get; set; }
        public string RFAIL { get; set; }
        public string STA { get; set; }
        public string WARR { get; set; }
        public string ACTION { get; set; }
        public string OEA { get; set; }
        public string AMC { get; set; }
        public string TTR { get; set; }
        public string SLA { get; set; }
        public string TSLOT { get; set; }
        public string RESLA { get; set; }
        public string KVA { get; set; }
        public string SSTA { get; set; }
        public string DPCODE { get; set; }
        public string lmodi { get; set; }
        public string AEDT { get; set; }
    }
}
