'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TMTLMVC
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TMTLMVC")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BILLs() As DbSet(Of BILL)
    Public Overridable Property BILL1() As DbSet(Of BILL1)
    Public Overridable Property CONTACTS() As DbSet(Of CONTACT)
    Public Overridable Property CUSTs() As DbSet(Of CUST)
    Public Overridable Property CUSTOMERs() As DbSet(Of CUSTOMER)
    Public Overridable Property MAINPOPUs() As DbSet(Of MAINPOPU)
    Public Overridable Property PMRs() As DbSet(Of PMR)
    Public Overridable Property PURCHSEs() As DbSet(Of PURCHSE)
    Public Overridable Property PURCHSE1() As DbSet(Of PURCHSE1)
    Public Overridable Property SHEET1() As DbSet(Of SHEET1)
    Public Overridable Property TABLE1() As DbSet(Of TABLE1)
    Public Overridable Property USER1() As DbSet(Of USER1)

End Class
