//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINCV4._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL1
    {
        public int BID { get; set; }
        public Nullable<System.DateTime> BDATE { get; set; }
        public string BNO { get; set; }
        public string CUST { get; set; }
        public string SNAME { get; set; }
        public Nullable<decimal> GTOT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> PAYMENT { get; set; }
        public string SECTOR { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> ROUND { get; set; }
        public Nullable<decimal> NTOT { get; set; }
        public Nullable<decimal> TVAL { get; set; }
        public string USER1 { get; set; }
        public string MODE { get; set; }
        public string VNO { get; set; }
        public Nullable<decimal> CBILL { get; set; }
        public Nullable<decimal> BAPAY { get; set; }
        public string BST { get; set; }
        public string SSTA { get; set; }
        public string DPCODE { get; set; }
        public string LMODI { get; set; }
        public string BID1 { get; set; }
        public string AEDT { get; set; }
        public Nullable<decimal> BAMT { get; set; }
    }
}
