//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINCV4._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB1Entities : DbContext
    {
        public DB1Entities()
            : base("name=DB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BILL> BILL { get; set; }
        public virtual DbSet<BILL1> BILL1 { get; set; }
        public virtual DbSet<CUST> CUST { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<MAINPOPU> MAINPOPU { get; set; }
        public virtual DbSet<PMR> PMR { get; set; }
        public virtual DbSet<PURCHSE> PURCHSE { get; set; }
        public virtual DbSet<PURCHSE1> PURCHSE1 { get; set; }
        public virtual DbSet<SHEET1> SHEET1 { get; set; }
        public virtual DbSet<TABLE1> TABLE1 { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
    }
}
