//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINCV4._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINPOPU
    {
        public int RID { get; set; }
        public string RID1 { get; set; }
        public string SID { get; set; }
        public string CNAME { get; set; }
        public string SNAME { get; set; }
        public string ENS { get; set; }
        public string ALSN { get; set; }
        public string RAT_PH { get; set; }
        public string PHASE { get; set; }
        public string MODEL { get; set; }
        public string BSN { get; set; }
        public string CPN { get; set; }
        public string PHNO { get; set; }
        public string ADDR { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public string SPIN { get; set; }
        public string AMC { get; set; }
        public string CHMR { get; set; }
        public Nullable<System.DateTime> CHMD { get; set; }
        public string lhmr { get; set; }
        public Nullable<System.DateTime> lsd { get; set; }
        public Nullable<System.DateTime> nsd { get; set; }
        public string ahm { get; set; }
        public string DGNO { get; set; }
        public string ACTION { get; set; }
        public string DIST { get; set; }
        public string STATE { get; set; }
        public string AMAKE { get; set; }
        public string WARR { get; set; }
        public string OEA { get; set; }
        public string SSTA { get; set; }
        public string hmage { get; set; }
        public string DPCODE { get; set; }
        public string lmodi { get; set; }
        public string AEDT { get; set; }
        public string llop { get; set; }
        public string solenoid { get; set; }
        public string chalt { get; set; }
        public string starter { get; set; }
        public string cntype { get; set; }
        public string cnmake { get; set; }
        public string sauto { get; set; }
        public string FRAME { get; set; }
        public string DSTA { get; set; }
    }
}
