//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCINCV4._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHEET1
    {
        public int RID { get; set; }
        public string PART_NO { get; set; }
        public string PARTI { get; set; }
        public string MRP { get; set; }
        public string GROP { get; set; }
        public string CATE { get; set; }
        public string DPCODE { get; set; }
        public string lmodi { get; set; }
        public string TRATE { get; set; }
        public string rid1 { get; set; }
        public string unit { get; set; }
        public string AEDT { get; set; }
    }
}
