'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class TABLE1
    Public Property RID1 As Integer
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="RECORD NO")>
    Public Property RID As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="ITEM TYPE")>
    Public Property TYPE As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="PART NO")>
    Public Property PART_NO As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="PRODUCT NAME")>
    Public Property PARTI As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="MRP")>
    Public Property MRP As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="QTY")>
    Public Property QTY As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="ITEM TOTAL")>
    Public Property TOTAL As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="RACK NO")>
    Public Property RACKNO As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="TAX RATE")>
    Public Property TAX As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="TAX VALUE")>
    Public Property TVAL As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="SELL PRICE TOTAL")>
    Public Property STOTAL As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="PURCHASE PRICE")>
    Public Property PPRICE As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="UNIT")>
    Public Property UNIT As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="SELL PRICE")>
    Public Property SPRICE As String
    Public Property SSTA As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="ITEM EOR")>
    Public Property EOR As String
    <Display(Name:="DEALER CODE")>
    Public Property DPCODE As String
    Public Property lmodi As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="ITEM GROUP")>
    Public Property grop As String
    Public Property AEDT As String
    <Required(ErrorMessage:="This Field Can't Be Blank!")>
    <Display(Name:="USER NAME")>
    Public Property USER1 As String

End Class
